# =========================================
# Load Required Libraries
# =========================================
# https://github.com/Bin-Chen-Lab/octad
suppressPackageStartupMessages({
  library(octad)
  library(octad.db)
  library(dplyr)
  library(vroom)
  library(tibble)
  library(readr)
})

setwd("~/CESC_Network/6_OCTAD/")

# =========================================
# Load OCTAD Preprocessed Data
# =========================================
count_matrix_df <- vroom("~/CESC_Network/2_Prepro_TCGA_GTEx/2_6_Full_counts_A7_A9_annot.tsv")
metadata_full   <- vroom("~/CESC_Network/2_Prepro_TCGA_GTEx/2_4_Factors.tsv")

# Move "Gene" column to rownames
count_matrix <- as.data.frame(count_matrix_df)
rownames(count_matrix) <- count_matrix$Gene
count_matrix$Gene <- NULL

# Clean and filter metadata (remove normal tissue samples)
metadata_full$sample_type <- trimws(metadata_full$sample_type)
metadata <- metadata_full %>%
  filter(sample_type != "Solid Tissue Normal")

# Subset count_matrix to tumor specimenIDs only
tumor_specimenIDs <- metadata$specimenID
tumor_cols <- intersect(colnames(count_matrix), tumor_specimenIDs)
count_matrix <- count_matrix[, tumor_cols]

# Map specimenID to cases.submitter_id and append "-01"
specimen_to_case <- metadata %>%
  dplyr::select(specimenID, cases.submitter_id) %>%
  mutate(
    cases.submitter_id = ifelse(
      grepl("-01$", cases.submitter_id),
      cases.submitter_id,
      paste0(cases.submitter_id, "-01")
    )
  )

# Apply new column names to count_matrix
new_names <- specimen_to_case$cases.submitter_id[
  match(colnames(count_matrix), specimen_to_case$specimenID)
]
colnames(count_matrix) <- new_names

# Also update metadata with "-01" appended
metadata <- metadata %>%
  mutate(
    cases.submitter_id = ifelse(
      grepl("-01$", cases.submitter_id),
      cases.submitter_id,
      paste0(cases.submitter_id, "-01")
    )
  )

dim(count_matrix)  #[1] 11544   268
dim(metadata)      #[1]   268     8

# =========================================
# Load LINCS Phenotype Data
# =========================================
phenoDF <- get_ExperimentHub_data("EH7274")

# =========================================
# A7 Clade Processing
# =========================================
muestras_clado_A7 <- metadata %>%
  filter(HPV_clade == "A7_clade") %>%
  pull(cases.submitter_id)

expSet_A7 <- count_matrix[, colnames(count_matrix) %in% muestras_clado_A7]
dim(expSet_A7)  #[1] 11544  66 

interseccion_A7 <- intersect(muestras_clado_A7, phenoDF$sample.id)
length(interseccion_A7) #[1] 65
setdiff(muestras_clado_A7, interseccion_A7)  # [1] "TCGA-C5-A7CM-01"

similitud_A7 <- computeCellLine(case_id = interseccion_A7, source = 'octad.small')
similitud_A7 <- similitud_A7 %>% mutate(cell_id = rownames(similitud_A7))
dim(similitud_A7) #[1] 51  2
lineas_similares_A7 <- similitud_A7 %>% filter(medcor > 0.3) %>% pull(cell_id)
length(lineas_similares_A7) #[1] 15

# =========================================
# A9 Clade Processing
# =========================================
muestras_clado_A9 <- metadata %>%
  filter(HPV_clade == "A9_clade") %>%
  pull(cases.submitter_id)

expSet_A9 <- count_matrix[, colnames(count_matrix) %in% muestras_clado_A9]
dim(expSet_A9) #[1] 11544  202

interseccion_A9 <- intersect(muestras_clado_A9, phenoDF$sample.id)
length(interseccion_A9) #[1] 202

similitud_A9 <- computeCellLine(case_id = interseccion_A9, source = 'octad.small')
similitud_A9 <- similitud_A9 %>% mutate(cell_id = rownames(similitud_A9))
lineas_similares_A9 <- similitud_A9 %>% filter(medcor > 0.3) %>% pull(cell_id)
length(lineas_similares_A9) #[1] 11

# =========================================
# Disease Signatures generated by OCTAD (REPLACES manual DGE)
# =========================================

# ---- 1) Un único conjunto de CONTROLES para A7 ∪ A9 ----
set.seed(42)
case_ids_union <- union(interseccion_A7, interseccion_A9)

control_id_common <- computeRefTissue(
  case_id      = case_ids_union,
  control_size = 50,
  output       = TRUE,
  outputFolder = "."   # deja CSVs de auditoría en el WD actual
)

# Guarda y muestra controles con metadatos
controls_tbl <- phenoDF %>% dplyr::filter(sample.id %in% control_id_common)
readr::write_tsv(tibble::as_tibble(controls_tbl), "OCTAD_controls_used.tsv")
message("N controles = ", length(control_id_common))


# ---- 2) DGE con OCTAD (octad.small) para A7 y A9 vs control común ----
# (small = 978 genes; rápido y alineado a LINCS para sRGES)
res_A7_small <- diffExp(
  case_id           = interseccion_A7,
  control_id        = control_id_common,
  source            = "octad.small",
  normalize_samples = TRUE,
  k                 = 1,
  n_topGenes        = 500,     # adecuado para small
  DE_method         = "edgeR",
  output            = FALSE
)

res_A9_small <- diffExp(
  case_id           = interseccion_A9,
  control_id        = control_id_common,
  source            = "octad.small",
  normalize_samples = TRUE,
  k                 = 1,
  n_topGenes        = 500,
  DE_method         = "edgeR",
  output            = FALSE
)

# Guarda las tablas COMPLETAS de DGE (en small = hasta 978 genes)
readr::write_tsv(as_tibble(res_A7_small), "DGE_small_A7_vs_commonCTRL.tsv.gz")
readr::write_tsv(as_tibble(res_A9_small), "DGE_small_A9_vs_commonCTRL.tsv.gz")


# ---- 3) (Opcional) DGE COMPLETA con octad.whole (si existe el HDF5) ----
# Esto produce la "lista completa de DGE" (todos los genes).
OCTAD_H5 <- "octad.counts.and.tpm.h5"  # cambia aquí si lo tienes en otra ruta
if (file.exists(OCTAD_H5)) {
  message("HDF5 encontrado: exportando DGE completa (octad.whole)...")
  res_A7_whole <- diffExp(
    case_id           = interseccion_A7,
    control_id        = control_id_common,
    source            = "octad.whole",
    file              = OCTAD_H5,
    normalize_samples = TRUE,
    k                 = 1,
    n_topGenes        = 5000,  # adecuado para whole (~20k genes)
    DE_method         = "edgeR",
    output            = FALSE
  )
  res_A9_whole <- diffExp(
    case_id           = interseccion_A9,
    control_id        = control_id_common,
    source            = "octad.whole",
    file              = OCTAD_H5,
    normalize_samples = TRUE,
    k                 = 1,
    n_topGenes        = 5000,
    DE_method         = "edgeR",
    output            = FALSE
  )
  readr::write_tsv(as_tibble(res_A7_whole), "DGE_full_A7_vs_commonCTRL.tsv.gz")
  readr::write_tsv(as_tibble(res_A9_whole), "DGE_full_A9_vs_commonCTRL.tsv.gz")
} else {
  message("No se encontró '", OCTAD_H5,
          "'. Se guardó DGE_small*. Para DGE COMPLETA exporta el HDF5 a este directorio.")
}

# ---- 4) Construir FIRMAS (desde res_*_small) para sRGES ----
# Elegimos small para las firmas (coherente con LINCS)
pick_symbol_col <- function(df) {
  if ("Symbol" %in% names(df)) return("Symbol")
  if ("Symbol_autho" %in% names(df)) return("Symbol_autho")
  stop("No se encontró columna de símbolos (Symbol / Symbol_autho).")
}

make_signature <- function(res_df, lfc_thr = 1, padj_thr = 1e-3) {
  sym_col <- pick_symbol_col(res_df)
  sig <- res_df %>%
    filter(!is.na(.data[[sym_col]])) %>%
    mutate(Symbol = toupper(.data[[sym_col]])) %>%
    filter(abs(log2FoldChange) > lfc_thr, padj < padj_thr) %>%
    distinct(Symbol, .keep_all = TRUE) %>%
    transmute(
      Symbol,
      log2FoldChange,
      regulation = if_else(log2FoldChange > 0, "up", "down"),
      padj
    )
  sig
}

firma_A7 <- make_signature(res_A7_small, lfc_thr = 1, padj_thr = 1e-3)
firma_A9 <- make_signature(res_A9_small, lfc_thr = 1, padj_thr = 1e-3)

# (Opcional) guarda las firmas usadas para sRGES
readr::write_tsv(firma_A7, "FIRMA_A7_signature.tsv")
readr::write_tsv(firma_A9, "FIRMA_A9_signature.tsv")

# =========================================
# Compute sRGES Scores (LINCS-Based Signature Reversal)
# (tu bloque original se mantiene, solo que ahora usa firma_A7 / firma_A9 creadas por OCTAD)
# =========================================
result_A7 <- octad::runsRGES(
  dz_signature     = firma_A7,
  cells            = lineas_similares_A7,
  weight_cell_line = similitud_A7,
  permutations     = 1000,
  choose_fda_drugs = TRUE
)

result_A9 <- runsRGES(
  dz_signature     = firma_A9,
  cells            = lineas_similares_A9,
  weight_cell_line = similitud_A9,
  permutations     = 1000,
  choose_fda_drugs = TRUE
)

# =========================================
# Filter Drugs with sRGES < -0.2
# =========================================
result_A7_0.2 <- result_A7 %>% filter(sRGES < -0.2)
dim(result_A7_0.2)
result_A9_0.2 <- result_A9 %>% filter(sRGES < -0.2) 
dim(result_A9_0.2)

length(intersect(result_A7_0.2$pert_iname, result_A9_0.2$pert_iname))


















setwd("~/CESC_Network/6_OCTAD/")
OCTAD_H5 <- "octad.counts.and.tpm.h5"
if (!file.exists(OCTAD_H5)) {
  url <- "https://chenlab-data-public.s3-us-west-2.amazonaws.com/octad/octad.counts.and.tpm.h5"
  download.file(url, destfile = OCTAD_H5, mode = "wb")
}
file.info(OCTAD_H5)[, c("size", "mtime")]






###############################3333
